torso_lift_error: 0.01
l_shoulder_pan_error: 0.03
l_shoulder_lift_error: 0.03
l_upper_arm_roll_error: 0.03
l_elbow_flex_error: 0.03
l_forearm_roll_error: 0.03
l_wrist_flex_error: 0.03
l_wrist_roll_error: 0.03
r_shoulder_pan_error: 0.03
r_shoulder_lift_error: 0.03
r_upper_arm_roll_error: 0.03
r_elbow_flex_error: 0.03
r_forearm_roll_error: 0.03
r_wrist_flex_error: 0.03
r_wrist_roll_error: 0.03
