thresholds:
  left_arm:
    joint:
      l_shoulder_pan_error: 0.01
      l_shoulder_lift_error: 0.01
      l_upper_arm_roll_error: 0.01
      l_elbow_flex_error: 0.01
      l_forearm_roll_error: 0.01
      l_wrist_flex_error: 0.01
      l_wrist_roll_error: 0.01
    cartesian:
      l_trans_error: 0.02
      l_rot_error: 0.03
  right_arm:
    joint:
      r_shoulder_pan_error: 0.01
      r_shoulder_lift_error: 0.01
      r_upper_arm_roll_error: 0.01
      r_elbow_flex_error: 0.01
      r_forearm_roll_error: 0.01
      r_wrist_flex_error: 0.01
      r_wrist_roll_error: 0.01
    cartesian:
      r_trans_error: 0.02
      r_rot_error: 0.03
goals:
  left_arm:
    joint: [0.9, 0.5, 0.9, -1.6, -5.0, -1.4, -1.8]
    cartesian: [0.5, 0.05, 0.65, 0.462, -0.4, -0.49, 0.62]
  right_arm:
    joint: [-0.9, 0.5, -0.9, -1.6, 5.0, -1.4, 1.8]
    cartesian: [0.38, -0.11, 1.11, -0.193, 0.01, 0.72, 0.67]
