root_link: base_footprint
left_ee_tip_link: l_gripper_tool_frame
trans3d_control:
  enable_thresholding: true
  error_threshold: 0.05
  p_gain: 3.0
  weight: 1.0
rot3d_control:
  enable_thresholding: true
  error_threshold: 0.1
  p_gain: 3.0
  weight: 1.0
default_joint_weight: 0.001
joint_weights:
  torso_lift_joint: 0.01
default_joint_velocity: 0.5
joint_velocity_limits:
  torso_lift_joint: 0.01
default_joint_convergence_threshold: 0.001
joint_convergence_thresholds:
  torso_lift_joint: 0.0001
min_num_traj_points: 50
max_num_traj_points: 500
nWSR: 100
sample_period: 0.02
